# This is a basic workflow to help you get started with Actions

name: Invalidations
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: LouisBrunner/checks-action@v0.1.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: report
        conclusion: 'success'
        output: '{"title": "report", "summary": "0 (0 via deps) vs. 0 on master", "text": "This is some random text"}'
