# This is a basic workflow to help you get started with Actions

name: Invalidations
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
    # Create check run
    - uses: octokit/request-action@v2.x
      name: create checks flag
      id: create_check_run
      with:
        route: POST /repos/:repository/check-runs
        repository: ${{ github.repository }}
        mediaType: | # The | is significant!
          previews: 
            - antiope
        name: report
        head_sha: ${{ github.sha }}
        output: | # The | is significant!
          title: report
          text: This is some text written in **markdown** format
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: julia-actions/setup-julia@v1
      with:
        version: 'nightly'
        
    - uses: octokit/request-action@v2.x
      name: report invalidation
      id: update_check_run
      with:
        route: PATCH /repos/:repository/check-runs/:check_run_id
        repository: ${{ github.repository }}
        mediaType: | # The | is significant!
          previews: 
            - antiope
        check_run_id: ${{ fromJson(steps.create_check_run.outputs.data).id }}
        conclusion: "success"
        status: "completed"
        output: | # The | is significant!
          title: "0 (0 via deps) vs. 0 on master"
          text: This is some text written in **markdown** format
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
